version: 0.1
env:
    secrets-manager:
      TOKEN: loginToken:tokenForZap
phases:
  build:
    commands:

#Dynamic Application Security Scan (DAST scan) using OWASP ZAP

     - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://example.com?login=$TOKEN -quickprogress