lower_t = 'SPECIALIZED KNOWLEDGE OF MAINFRAME MODERNIZATIONS, CLOUD TOOLS AND' \
          ' TECHNOLOGY, AWS SERVICES, APPLICATION MIGRATIONS, DEVOPS PROCESS TO ' \
          'DETERMINE THE COMPONENTS OF THE SYSTEM THAT WOULD BE IMPACTED TO MEET ' \
          'THE REQUIREMENTS AND THE COMPLEXITIES INVOLVED IN DOING THE CHANGES TO THE SYSTEM ' \
          '• PROVIDE ESTIMATES REQUIRED FOR THE DESIGN, DEVELOPMENT, AND IMPLEMENTATION OF THE ' \
          'PROPOSED FUNCTIONALITIES FOR APPLICATION MODERNIZATIONS FOR LEGACY APPLICATIONS. ' \
          '• CREATING HIGH LEVEL AND LOW-LEVEL TECHNICAL DESIGN DOCUMENTS ' \
          '• AS AN SME, RESPONSIBLE FOR PROVIDING THE KT (KNOWLEDGE TRANSFER) TO SUPPORT TEAM FOR ' \
          'THE NEW MODIFICATION DONE IN THE PRODUCTION ENVIRONMENT'

lrcase = lower_t.lower()
print(lrcase)